import { tFallback, type Language } from '@tinybubbles/core';

type TranslateFn = (key: string) => string;

/**
 * Plain-language display overrides (see DESIGN.md — simplify pass).
 *
 * The translated strings live in packages/core (edit-forbidden) and speak GTD:
 * "Next Actions", "Someday/Maybe", "Waiting For". The shell shows plainer
 * words a child could hear read aloud. This map is the single place where
 * display text is overridden — core is untouched, and the override only
 * applies at call sites that opt in via displayLabel().
 *
 * Per-locale tables: each language carries its own kid-register words —
 * the word a parent would actually say to a young child in that language,
 * not a dictionary rendering of the English kid-word (so fr "Vide ton sac"
 * for the mind sweep, ja おかたづけ for tidying, zh 以后再说 for
 * "maybe later"). Rules:
 *
 * - A key missing from a locale's table falls back to the core translation
 *   for that locale, exactly as before. Keys are deliberately omitted where
 *   the core word is already fine for a child or where the English kid-word
 *   has no safe short equivalent (e.g. Russian numeral grammar cannot share
 *   one label between a section title and a "{count} {label}" line).
 * - Locales with no table at all (ar, cs, fa, hi, vi) stay on their core
 *   translations: a wrong-register guess is worse than the adult word, and
 *   those need a native check (recorded in DESIGN.md).
 * - Japanese overrides are written kana-first on purpose — the reader is a
 *   young child, unlike core's kanji-register strings.
 * - Every key used here must exist in the English table below; the English
 *   table is the contract for which surfaces the shell re-words
 *   (display-labels.test.ts pins this).
 */
const EN_OVERRIDES: Record<string, string> = {
    'status.next': 'To do',
    'status.someday': 'Maybe later',
    'agenda.nextActions': 'To do',
    'list.someday': 'Maybe later',
    'list.waiting': 'Waiting',
    'nav.trash': 'Deleted',
    'calendar.openDayView': 'Show this day',
    'calendar.items': 'to do',
    'calendar.deadline': 'Due',
    'calendar.unschedule': 'Take off this day',
    'calendar.existingTask': 'Pick a task',
    'calendar.schedulePlaceholder': 'Find a task...',
    'quickAdd.example': 'e.g. Feed the cat',
    'quickAdd.invalidDateCommand': "I couldn't understand this date",
    'projects.activeSection': 'My lists',
    'projects.deferredSection': 'Later',
    'projects.selectProject': 'Pick a list to see its tasks',
    'process.btn': 'Tidy up',
    'mindSweep.launchButton': 'Get it all out',
    'mindSweep.title': 'Get it all out',
    'calendar.tasksAndEvents': 'See what is coming up',
    'search.scopeHint': 'Find anything',
    'inbox.projectHint': 'If something needs lots of steps, you can turn it into a list while you tidy up.',
    'task.createProjectFromTask': 'Turn into a list',
};

const DISPLAY_LABEL_OVERRIDES_BY_LANGUAGE: Partial<Record<Language, Record<string, string>>> = {
    en: EN_OVERRIDES,
    de: {
        'status.next': 'Zu tun',
        'status.someday': 'Vielleicht später',
        'agenda.nextActions': 'Zu tun',
        'list.someday': 'Vielleicht später',
        'list.waiting': 'Warten',
        'nav.trash': 'Gelöscht',
        'calendar.openDayView': 'Diesen Tag ansehen',
        'calendar.items': 'zu tun',
        'calendar.unschedule': 'Von diesem Tag nehmen',
        'calendar.existingTask': 'Such dir eine Aufgabe aus',
        'calendar.schedulePlaceholder': 'Aufgabe suchen...',
        'quickAdd.example': 'z. B. Katze füttern',
        'quickAdd.invalidDateCommand': 'Dieses Datum habe ich nicht verstanden',
        'projects.activeSection': 'Meine Listen',
        'projects.deferredSection': 'Für später',
        'projects.selectProject': 'Such dir eine Liste aus, um ihre Aufgaben zu sehen',
        'process.btn': 'Aufräumen',
        'mindSweep.launchButton': 'Alles rauslassen',
        'mindSweep.title': 'Alles rauslassen',
        'calendar.tasksAndEvents': 'Schau, was ansteht',
        'search.scopeHint': 'Finde alles',
        'inbox.projectHint': 'Wenn etwas viele Schritte braucht, kannst du beim Aufräumen eine Liste daraus machen.',
        'task.createProjectFromTask': 'In eine Liste verwandeln',
    },
    es: {
        'status.next': 'Para hacer',
        'status.someday': 'Quizá luego',
        'agenda.nextActions': 'Para hacer',
        'list.someday': 'Quizá luego',
        'list.waiting': 'Esperando',
        'nav.trash': 'Borradas',
        'calendar.openDayView': 'Ver este día',
        'calendar.items': 'para hacer',
        'calendar.unschedule': 'Quitar de este día',
        'calendar.existingTask': 'Elige una tarea',
        'calendar.schedulePlaceholder': 'Busca una tarea...',
        'quickAdd.example': 'p. ej. Dar de comer al gato',
        'quickAdd.invalidDateCommand': 'No entendí esta fecha',
        'projects.activeSection': 'Mis listas',
        'projects.deferredSection': 'Para luego',
        'projects.selectProject': 'Elige una lista para ver sus tareas',
        'process.btn': 'Ordenar',
        'mindSweep.launchButton': 'Suéltalo todo',
        'mindSweep.title': 'Suéltalo todo',
        'calendar.tasksAndEvents': 'Mira lo que viene',
        'search.scopeHint': 'Encuentra lo que sea',
        'inbox.projectHint': 'Si algo necesita muchos pasos, puedes convertirlo en una lista mientras ordenas.',
        'task.createProjectFromTask': 'Convertir en lista',
    },
    fr: {
        'status.next': 'À faire',
        'status.someday': 'Peut-être plus tard',
        'agenda.nextActions': 'À faire',
        'list.someday': 'Peut-être plus tard',
        'nav.trash': 'Supprimées',
        'calendar.openDayView': 'Voir ce jour',
        'calendar.items': 'à faire',
        'calendar.unschedule': 'Enlever de ce jour',
        'calendar.existingTask': 'Choisis une tâche',
        'calendar.schedulePlaceholder': 'Cherche une tâche...',
        'quickAdd.example': 'ex. Donner à manger au chat',
        'quickAdd.invalidDateCommand': "Je n'ai pas compris cette date",
        'projects.activeSection': 'Mes listes',
        'projects.deferredSection': 'Pour plus tard',
        'projects.selectProject': 'Choisis une liste pour voir ses tâches',
        'process.btn': 'Ranger',
        'mindSweep.launchButton': 'Vide ton sac',
        'mindSweep.title': 'Vide ton sac',
        'calendar.tasksAndEvents': 'Regarde ce qui arrive',
        'search.scopeHint': 'Trouve ce que tu cherches',
        'inbox.projectHint': "Si quelque chose demande beaucoup d'étapes, tu peux en faire une liste pendant que tu ranges.",
        'task.createProjectFromTask': 'Transformer en liste',
    },
    it: {
        'status.next': 'Da fare',
        'status.someday': 'Magari dopo',
        'agenda.nextActions': 'Da fare',
        'list.someday': 'Magari dopo',
        'nav.trash': 'Eliminate',
        'calendar.openDayView': 'Guarda questo giorno',
        'calendar.items': 'da fare',
        'calendar.unschedule': 'Togli da questo giorno',
        'calendar.existingTask': "Scegli un'attività",
        'calendar.schedulePlaceholder': "Cerca un'attività...",
        'quickAdd.example': 'es. Dai da mangiare al gatto',
        'quickAdd.invalidDateCommand': 'Non ho capito questa data',
        'projects.activeSection': 'Le mie liste',
        'projects.deferredSection': 'Per dopo',
        'projects.selectProject': 'Scegli una lista per vedere le sue attività',
        'process.btn': 'Metti in ordine',
        'mindSweep.launchButton': 'Tira fuori tutto',
        'mindSweep.title': 'Tira fuori tutto',
        'calendar.tasksAndEvents': 'Guarda cosa arriva',
        'search.scopeHint': 'Trova quello che vuoi',
        'inbox.projectHint': 'Se una cosa ha bisogno di tanti passaggi, puoi trasformarla in una lista mentre metti in ordine.',
        'task.createProjectFromTask': 'Trasforma in lista',
    },
    nl: {
        'status.next': 'Te doen',
        'status.someday': 'Misschien later',
        'agenda.nextActions': 'Te doen',
        'list.someday': 'Misschien later',
        'nav.trash': 'Verwijderd',
        'calendar.openDayView': 'Bekijk deze dag',
        'calendar.items': 'te doen',
        'calendar.unschedule': 'Haal van deze dag af',
        'calendar.existingTask': 'Kies een taak',
        'calendar.schedulePlaceholder': 'Zoek een taak...',
        'quickAdd.example': 'bijv. De kat eten geven',
        'quickAdd.invalidDateCommand': 'Ik snapte deze datum niet',
        'projects.activeSection': 'Mijn lijstjes',
        'projects.deferredSection': 'Voor later',
        'projects.selectProject': 'Kies een lijstje om de taken te zien',
        'process.btn': 'Opruimen',
        'mindSweep.launchButton': 'Gooi het eruit',
        'mindSweep.title': 'Gooi het eruit',
        'calendar.tasksAndEvents': 'Kijk wat eraan komt',
        'search.scopeHint': 'Vind alles',
        'inbox.projectHint': 'Als iets veel stappen nodig heeft, kun je er tijdens het opruimen een lijstje van maken.',
        'task.createProjectFromTask': 'Maak er een lijstje van',
    },
    pl: {
        'status.next': 'Do zrobienia',
        'status.someday': 'Może później',
        'agenda.nextActions': 'Do zrobienia',
        'list.someday': 'Może później',
        'list.waiting': 'Czeka',
        'nav.trash': 'Usunięte',
        'calendar.openDayView': 'Pokaż ten dzień',
        'calendar.items': 'do zrobienia',
        'calendar.unschedule': 'Zdejmij z tego dnia',
        'calendar.existingTask': 'Wybierz zadanie',
        'calendar.schedulePlaceholder': 'Poszukaj zadania...',
        'quickAdd.example': 'np. Nakarmić kota',
        'quickAdd.invalidDateCommand': 'Nie rozumiem tej daty',
        'projects.activeSection': 'Moje listy',
        'projects.deferredSection': 'Na później',
        'projects.selectProject': 'Wybierz listę, żeby zobaczyć jej zadania',
        'process.btn': 'Posprzątaj',
        'mindSweep.launchButton': 'Wyrzuć wszystko z głowy',
        'mindSweep.title': 'Wyrzuć wszystko z głowy',
        'calendar.tasksAndEvents': 'Zobacz, co się szykuje',
        'search.scopeHint': 'Znajdź, co chcesz',
        'inbox.projectHint': 'Jeśli coś wymaga wielu kroków, możesz zrobić z tego listę podczas sprzątania.',
        'task.createProjectFromTask': 'Zamień na listę',
    },
    pt: {
        'status.next': 'Para fazer',
        'status.someday': 'Talvez depois',
        'agenda.nextActions': 'Para fazer',
        'list.someday': 'Talvez depois',
        'list.waiting': 'Esperando',
        'nav.trash': 'Apagadas',
        'calendar.openDayView': 'Ver este dia',
        'calendar.items': 'para fazer',
        'calendar.unschedule': 'Tirar deste dia',
        'calendar.existingTask': 'Escolha uma tarefa',
        'calendar.schedulePlaceholder': 'Procure uma tarefa...',
        'quickAdd.example': 'ex.: Dar comida ao gato',
        'quickAdd.invalidDateCommand': 'Não entendi essa data',
        'projects.activeSection': 'Minhas listas',
        'projects.deferredSection': 'Para depois',
        'projects.selectProject': 'Escolha uma lista para ver as tarefas dela',
        'process.btn': 'Arrumar',
        'mindSweep.launchButton': 'Bota tudo pra fora',
        'mindSweep.title': 'Bota tudo pra fora',
        'calendar.tasksAndEvents': 'Veja o que vem por aí',
        'search.scopeHint': 'Encontre qualquer coisa',
        'inbox.projectHint': 'Se algo precisa de muitos passos, você pode transformar em uma lista enquanto arruma.',
        'task.createProjectFromTask': 'Transformar em lista',
    },
    ru: {
        'status.next': 'Сделать',
        'status.someday': 'Может, потом',
        'agenda.nextActions': 'Дела',
        'list.someday': 'Может, потом',
        'list.waiting': 'Ждём',
        'nav.trash': 'Удалённые',
        'calendar.openDayView': 'Показать этот день',
        'calendar.unschedule': 'Убрать с этого дня',
        'calendar.existingTask': 'Выбери задачу',
        'calendar.schedulePlaceholder': 'Найди задачу...',
        'quickAdd.example': 'например: Покормить кота',
        'quickAdd.invalidDateCommand': 'Не получилось понять эту дату',
        'projects.activeSection': 'Мои списки',
        'projects.deferredSection': 'На потом',
        'projects.selectProject': 'Выбери список, чтобы увидеть его задачи',
        'process.btn': 'Навести порядок',
        'mindSweep.launchButton': 'Выложи всё из головы',
        'mindSweep.title': 'Выложи всё из головы',
        'calendar.tasksAndEvents': 'Посмотри, что впереди',
        'search.scopeHint': 'Найди что угодно',
        'inbox.projectHint': 'Если для чего-то нужно много шагов, можно превратить это в список, пока наводишь порядок.',
        'task.createProjectFromTask': 'Превратить в список',
    },
    sv: {
        'status.next': 'Att göra',
        'status.someday': 'Kanske senare',
        'agenda.nextActions': 'Att göra',
        'list.someday': 'Kanske senare',
        'list.waiting': 'Väntar',
        'nav.trash': 'Borttagna',
        'calendar.openDayView': 'Visa den här dagen',
        'calendar.items': 'att göra',
        'calendar.unschedule': 'Ta bort från den här dagen',
        'calendar.existingTask': 'Välj en uppgift',
        'calendar.schedulePlaceholder': 'Leta efter en uppgift...',
        'quickAdd.example': 't.ex. Mata katten',
        'quickAdd.invalidDateCommand': 'Jag förstod inte det här datumet',
        'projects.activeSection': 'Mina listor',
        'projects.deferredSection': 'Till senare',
        'projects.selectProject': 'Välj en lista för att se dess uppgifter',
        'process.btn': 'Städa upp',
        'mindSweep.launchButton': 'Få ut allt',
        'mindSweep.title': 'Få ut allt',
        'calendar.tasksAndEvents': 'Se vad som är på gång',
        'search.scopeHint': 'Hitta vad som helst',
        'inbox.projectHint': 'Om något behöver många steg kan du göra en lista av det medan du städar.',
        'task.createProjectFromTask': 'Gör om till en lista',
    },
    tr: {
        'status.next': 'Yapılacak',
        'status.someday': 'Belki sonra',
        'agenda.nextActions': 'Yapılacaklar',
        'list.someday': 'Belki sonra',
        'list.waiting': 'Bekliyor',
        'nav.trash': 'Silinenler',
        'calendar.openDayView': 'Bu günü göster',
        'calendar.items': 'yapılacak',
        'calendar.unschedule': 'Bu günden çıkar',
        'calendar.existingTask': 'Bir görev seç',
        'calendar.schedulePlaceholder': 'Görev ara...',
        'quickAdd.example': 'örn. Kediyi besle',
        'quickAdd.invalidDateCommand': 'Bu tarihi anlayamadım',
        'projects.activeSection': 'Listelerim',
        'projects.deferredSection': 'Sonraya',
        'projects.selectProject': 'Görevlerini görmek için bir liste seç',
        'process.btn': 'Toparla',
        'mindSweep.launchButton': 'İçini dök',
        'mindSweep.title': 'İçini dök',
        'calendar.tasksAndEvents': 'Bak neler geliyor',
        'search.scopeHint': 'İstediğini bul',
        'inbox.projectHint': 'Bir şey çok adım gerektiriyorsa, toparlarken onu bir listeye dönüştürebilirsin.',
        'task.createProjectFromTask': 'Listeye dönüştür',
    },
    ja: {
        'status.next': 'やること',
        'status.someday': 'また今度',
        'agenda.nextActions': 'やること',
        'list.someday': 'また今度',
        'list.waiting': 'まってる',
        'nav.trash': 'けしたもの',
        'calendar.openDayView': 'この日をみる',
        'calendar.items': 'やること',
        'calendar.deadline': 'しめきり',
        'calendar.unschedule': 'この日からはずす',
        'calendar.existingTask': 'やることをえらぶ',
        'calendar.schedulePlaceholder': 'やることをさがす...',
        'quickAdd.example': 'れい：ねこにごはんをあげる',
        'quickAdd.invalidDateCommand': 'この日づけがわかりませんでした',
        'projects.activeSection': 'わたしのリスト',
        'projects.deferredSection': 'あとで',
        'projects.selectProject': 'リストをえらぶと、やることが見えるよ',
        'process.btn': 'おかたづけ',
        'mindSweep.launchButton': 'ぜんぶ出しちゃおう',
        'mindSweep.title': 'ぜんぶ出しちゃおう',
        'calendar.tasksAndEvents': 'これからのよていを見よう',
        'search.scopeHint': 'なんでもさがせるよ',
        'inbox.projectHint': 'たくさんのステップがいるときは、おかたづけしながらリストにできるよ。',
        'task.createProjectFromTask': 'リストにする',
    },
    ko: {
        'status.next': '할 일',
        'status.someday': '나중에 하기',
        'agenda.nextActions': '할 일',
        'list.someday': '나중에 하기',
        'list.waiting': '기다리는 중',
        'nav.trash': '지운 것들',
        'calendar.openDayView': '이 날 보기',
        'calendar.items': '할 일',
        'calendar.unschedule': '이 날에서 빼기',
        'calendar.existingTask': '할 일 고르기',
        'calendar.schedulePlaceholder': '할 일 찾기...',
        'quickAdd.example': '예: 고양이 밥 주기',
        'quickAdd.invalidDateCommand': '이 날짜를 잘 모르겠어요',
        'projects.activeSection': '내 목록',
        'projects.deferredSection': '나중에',
        'projects.selectProject': '목록을 고르면 할 일이 보여요',
        'process.btn': '정리하기',
        'mindSweep.launchButton': '다 꺼내 놓기',
        'mindSweep.title': '다 꺼내 놓기',
        'calendar.tasksAndEvents': '앞으로 뭐 있는지 보기',
        'search.scopeHint': '뭐든지 찾기',
        'inbox.projectHint': '단계가 많이 필요한 일은 정리하면서 목록으로 만들 수 있어요.',
        'task.createProjectFromTask': '목록으로 만들기',
    },
    zh: {
        'status.next': '要做的事',
        'status.someday': '以后再说',
        'agenda.nextActions': '要做的事',
        'list.someday': '以后再说',
        'list.waiting': '在等',
        'nav.trash': '删掉的',
        'calendar.openDayView': '看看这一天',
        'calendar.items': '件事',
        'calendar.unschedule': '从这一天拿掉',
        'calendar.existingTask': '挑一件事',
        'calendar.schedulePlaceholder': '找找要做的事...',
        'quickAdd.example': '比如：喂猫',
        'quickAdd.invalidDateCommand': '我没看懂这个日期',
        'projects.activeSection': '我的清单',
        'projects.deferredSection': '以后',
        'projects.selectProject': '挑一个清单，看看里面的事',
        'process.btn': '收拾一下',
        'mindSweep.launchButton': '全都倒出来',
        'mindSweep.title': '全都倒出来',
        'calendar.tasksAndEvents': '看看接下来有什么',
        'search.scopeHint': '什么都能找到',
        'inbox.projectHint': '如果一件事要很多步，你可以在收拾的时候把它变成一个清单。',
        'task.createProjectFromTask': '变成清单',
    },
    'zh-Hant': {
        'status.next': '要做的事',
        'status.someday': '以後再說',
        'agenda.nextActions': '要做的事',
        'list.someday': '以後再說',
        'list.waiting': '在等',
        'nav.trash': '刪掉的',
        'calendar.openDayView': '看看這一天',
        'calendar.items': '件事',
        'calendar.unschedule': '從這一天拿掉',
        'calendar.existingTask': '挑一件事',
        'calendar.schedulePlaceholder': '找找要做的事...',
        'quickAdd.example': '例如：餵貓',
        'quickAdd.invalidDateCommand': '我沒看懂這個日期',
        'projects.activeSection': '我的清單',
        'projects.deferredSection': '以後',
        'projects.selectProject': '挑一個清單，看看裡面的事',
        'process.btn': '收拾一下',
        'mindSweep.launchButton': '全都倒出來',
        'mindSweep.title': '全都倒出來',
        'calendar.tasksAndEvents': '看看接下來有什麼',
        'search.scopeHint': '什麼都能找到',
        'inbox.projectHint': '如果一件事要很多步，你可以在收拾的時候把它變成一個清單。',
        'task.createProjectFromTask': '變成清單',
    },
};

/**
 * The English override table, exported for the contract test: every locale's
 * keys must be a subset of these, so a typo'd key cannot silently become a
 * dead entry.
 */
export const DISPLAY_LABEL_KEY_CONTRACT = EN_OVERRIDES;

/** Locale tables, exported for the contract test only. */
export const DISPLAY_LABEL_TABLES = DISPLAY_LABEL_OVERRIDES_BY_LANGUAGE;

/** The translated label for `key`, unless the shell overrides it with plainer words. */
export function displayLabel(t: TranslateFn, language: Language, key: string, fallback: string): string {
    return DISPLAY_LABEL_OVERRIDES_BY_LANGUAGE[language]?.[key] ?? tFallback(t, key, fallback);
}
