import { getEnglishI18nValue, SETTINGS_SEARCH_PAGE_KEYS } from '@mindwtr/core';

// The keys settings pages read through the `t` prop. Every key resolves to a
// `settings.<key>` string in packages/core/src/i18n (or an explicit override
// below) — this array is only the roster of keys, not their text. Localized
// text lives entirely in packages/core/src/i18n/locales/*.ts so translators
// and locale-parity.test.ts can see it.
export const SETTINGS_LABEL_KEYS = [
    'title',
    'general',
    'integrations',
    'advanced',
    'subtitle',
    'searchPlaceholder',
    'back',
    'features',
    'featuresDesc',
    'lookAndFeel',
    'localization',
    'input',
    'windowBehavior',
    'appearance',
    'density',
    'densityDesc',
    'densityComfortable',
    'densityCompact',
    'densityCondensed',
    'textSize',
    'textSizeDesc',
    'textSizeSmall',
    'textSizeDefault',
    'textSizeLarge',
    'textSizeExtraLarge',
    'showTaskAge',
    'showTaskAgeDesc',
    'gtd',
    'gtdDesc',
    'inboxProcessing',
    'inboxProcessingDesc',
    'inboxDefaultMode',
    'inboxModeGuided',
    'inboxModeQuick',
    'inboxTwoMinuteEnabled',
    'inboxTwoMinuteFirst',
    'inboxProjectFirst',
    'inboxContextStepEnabled',
    'inboxScheduleEnabled',
    'inboxReferenceEnabled',
    'captureDefault',
    'captureDefaultDesc',
    'captureDefaultText',
    'captureDefaultAudio',
    'captureSaveAudio',
    'captureSaveAudioDesc',
    'quickAddAutoClean',
    'quickAddAutoCleanDesc',
    'naturalLanguageDates',
    'naturalLanguageDatesDesc',
    'markdownEditorAssist',
    'markdownEditorAssistDesc',
    'autoArchive',
    'autoArchiveDesc',
    'autoArchiveNever',
    'autoArchiveDayUnit',
    'defaultScheduleTime',
    'defaultScheduleTimeDesc',
    'defaultArea',
    'defaultAreaDesc',
    'defaultAreaNone',
    'defaultAreaActive',
    'focusTaskLimit',
    'focusTaskLimitDesc',
    'defaultProjectFlowMode',
    'defaultProjectFlowModeDesc',
    'projectFlowParallel',
    'projectFlowSequential',
    'timeEstimatePresets',
    'timeEstimatePresetsDesc',
    'timeEstimatePresetsDisabled',
    'enableTimeEstimates',
    'language',
    'weekStart',
    'weekStartSunday',
    'weekStartSystem',
    'weekStartMonday',
    'weekStartSaturday',
    'dateFormat',
    'dateFormatSystem',
    'dateFormatDmy',
    'dateFormatMdy',
    'dateFormatYmd',
    'calendarSystem',
    'calendarSystemGregorian',
    'calendarSystemJalali',
    'timeFormat',
    'timeFormatSystem',
    'timeFormat12h',
    'timeFormat24h',
    'keybindings',
    'keybindingsDesc',
    'undoNotifications',
    'undoNotificationsDesc',
    'globalQuickAddShortcut',
    'globalQuickAddShortcutDesc',
    'globalQuickAddFlatpakDesc',
    'globalQuickAddFlatpakCommand',
    'globalQuickAddFlatpakCommandDesc',
    'keybindingStandard',
    'keybindingVim',
    'keybindingEmacs',
    'viewShortcuts',
    'windowDecorations',
    'windowDecorationsDesc',
    'closeBehavior',
    'closeBehaviorDesc',
    'closeBehaviorAsk',
    'closeBehaviorTray',
    'closeBehaviorQuit',
    'launchAtStartup',
    'launchAtStartupDesc',
    'showTray',
    'showTrayDesc',
    'automation',
    'rendering',
    'softwareRendering',
    'softwareRenderingDesc',
    'network',
    'localApiServer',
    'localApiPort',
    'localApiPortDesc',
    'localApiToken',
    'localApiTokenDesc',
    'localApiSecurityNote',
    'localApiStopped',
    'localApiUnavailable',
    'localApiPortInvalid',
    'taskEditorLayout',
    'taskEditorLayoutDesc',
    'taskEditorLayoutHint',
    'taskEditorPresentation',
    'taskEditorPresentationDesc',
    'taskEditorPresentationInline',
    'taskEditorPresentationInlineDesc',
    'taskEditorPresentationModal',
    'taskEditorPresentationModalDesc',
    'taskEditorLayoutReset',
    'taskEditorSection',
    'taskEditorDefaultOpen',
    'taskEditorOpenByDefault',
    'taskEditorDefaultOpenDesc',
    'taskEditorFieldStatus',
    'taskEditorFieldProject',
    'taskEditorFieldSection',
    'taskEditorFieldArea',
    'taskEditorFieldPriority',
    'taskEditorFieldEnergyLevel',
    'taskEditorFieldAssignedTo',
    'taskEditorFieldContexts',
    'taskEditorFieldDescription',
    'taskEditorFieldLocation',
    'taskEditorFieldTags',
    'taskEditorFieldTimeEstimate',
    'taskEditorFieldRecurrence',
    'taskEditorFieldStartTime',
    'taskEditorFieldDueDate',
    'taskEditorFieldReviewAt',
    'taskEditorFieldAttachments',
    'taskEditorFieldChecklist',
    'taskEditorFieldTextDirection',
    'featurePriorities',
    'featurePrioritiesDesc',
    'featureTimeEstimates',
    'featureTimeEstimatesDesc',
    'featurePomodoro',
    'featurePomodoroDesc',
    'pomodoroCustomPreset',
    'pomodoroCustomPresetDesc',
    'pomodoroFocusMinutes',
    'pomodoroBreakMinutes',
    'pomodoroLinkTask',
    'pomodoroLinkTaskDesc',
    'pomodoroAutoStartBreaks',
    'pomodoroAutoStartBreaksDesc',
    'pomodoroAutoStartFocus',
    'pomodoroAutoStartFocusDesc',
    'notifications',
    'notificationsDesc',
    'notificationsEnable',
    'startDateNotifications',
    'startDateNotificationsDesc',
    'dueDateNotifications',
    'dueDateNotificationsDesc',
    'reviewAtNotifications',
    'reviewAtNotificationsDesc',
    'ai',
    'aiDesc',
    'aiUsageTitle',
    'aiUsageClarify',
    'aiUsageBreakdown',
    'aiUsageSuggestions',
    'aiUsageReview',
    'aiEnable',
    'aiProvider',
    'aiProviderOpenAI',
    'aiProviderGemini',
    'aiProviderAnthropic',
    'aiModel',
    'aiBaseUrl',
    'aiBaseUrlHint',
    'aiBaseUrlModelHint',
    'aiExtraBodyParams',
    'aiExtraBodyParamsDesc',
    'aiExtraBodyParamsHint',
    'aiExtraBodyParamsInvalid',
    'aiExtraBodyParamsSave',
    'aiApiKey',
    'aiApiKeyHint',
    'aiReasoning',
    'aiReasoningHint',
    'aiEffortLow',
    'aiEffortMedium',
    'aiEffortHigh',
    'aiCopilotModel',
    'aiCopilotHint',
    'aiConsentTitle',
    'aiConsentDescription',
    'aiConsentCancel',
    'aiConsentAgree',
    'aiThinkingBudget',
    'aiThinkingHint',
    'aiThinkingEnable',
    'aiThinkingEnableDesc',
    'aiThinkingOff',
    'aiThinkingLow',
    'aiThinkingMedium',
    'aiThinkingHigh',
    'speechTitle',
    'speechDesc',
    'speechEnable',
    'speechProvider',
    'speechProviderOffline',
    'speechProviderParakeet',
    'speechModel',
    'speechBaseUrl',
    'speechBaseUrlHint',
    'speechOfflineModel',
    'speechOfflineModelDesc',
    'speechParakeetModelDesc',
    'speechParakeetModelPath',
    'speechParakeetModelPathPlaceholder',
    'speechOfflineReady',
    'speechOfflineNotDownloaded',
    'speechOfflineEstimatedSize',
    'speechOfflinePathSet',
    'speechOfflineDownload',
    'speechOfflineDownloadSuccess',
    'speechOfflineDelete',
    'speechOfflineDownloadRuntime',
    'speechOfflineDownloadModel',
    'speechOfflineInstalling',
    'speechOfflineDownloadError',
    'speechLanguage',
    'speechLanguageHint',
    'speechLanguageAuto',
    'speechMode',
    'speechModeHint',
    'speechModeSmart',
    'speechModeTranscript',
    'speechFieldStrategy',
    'speechFieldStrategyHint',
    'speechFieldSmart',
    'speechFieldTitle',
    'speechFieldDescription',
    'dailyDigest',
    'dailyDigestDesc',
    'dailyDigestMorning',
    'dailyDigestEvening',
    'weeklyReview',
    'weeklyReviewDesc',
    'weeklyReviewDay',
    'weeklyReviewTime',
    'weeklyReviewConfig',
    'weeklyReviewConfigDesc',
    'weeklyReviewIncludeContextsStep',
    'weeklyReviewIncludeContextsStepDesc',
    'on',
    'off',
    'visible',
    'hidden',
    'manage',
    'dataTransfer',
    'dataTransferDesc',
    'exportBackup',
    'exportBackupDesc',
    'restoreBackup',
    'restoreBackupDesc',
    'importTodoist',
    'importTodoistDesc',
    'importTickTick',
    'importTickTickDesc',
    'importDgt',
    'importDgtDesc',
    'importOmniFocus',
    'importOmniFocusDesc',
    'diagnostics',
    'diagnosticsDesc',
    'analyticsHeartbeat',
    'analyticsHeartbeatDesc',
    'analyticsHeartbeatDisableTitle',
    'analyticsHeartbeatDisableDesc',
    'analyticsHeartbeatDisableConfirm',
    'analyticsHeartbeatKeepEnabled',
    'debugLogging',
    'debugLoggingDesc',
    'logFile',
    'clearLog',
    'sync',
    'syncDescription',
    'syncBackend',
    'syncBackendOff',
    'syncBackendFile',
    'syncBackendWebdav',
    'syncBackendCloud',
    'syncBackendCloudkit',
    'syncBackendChoiceHint',
    'syncBackendGroupCloud',
    'syncBackendGroupCloudDesc',
    'syncBackendGroupFile',
    'syncBackendGroupFileDesc',
    'syncBackendGroupAdvanced',
    'syncBackendGroupAdvancedDesc',
    'networkProxyUrl',
    'networkProxyUrlDesc',
    'networkProxyUrlHint',
    'networkProxyInvalid',
    'networkProxySave',
    'syncPreferences',
    'syncPreferencesDesc',
    'syncPreferenceAppearance',
    'syncPreferenceLanguage',
    'syncPreferenceGtd',
    'syncPreferenceSavedFilters',
    'syncPreferenceExternalCalendars',
    'syncPreferenceAi',
    'syncPreferenceAiHint',
    'backgroundSync',
    'backgroundSyncDesc',
    'attachmentsCleanup',
    'attachmentsCleanupDesc',
    'attachmentsCleanupLastRun',
    'attachmentsCleanupNever',
    'attachmentsCleanupPendingDeletes',
    'attachmentsCleanupPendingDeletesClear',
    'attachmentsCleanupPendingDeletesConfirm',
    'attachmentsCleanupPendingDeletesConfirmTitle',
    'attachmentsCleanupRun',
    'attachmentsCleanupRunning',
    'calendar',
    'calendarDesc',
    'externalCalendars',
    'calendarName',
    'calendarUrl',
    'calendarAdd',
    'calendarChooseLocalFile',
    'calendarRemove',
    'calendarSystemTitle',
    'calendarSystemDesc',
    'calendarSystemStatus',
    'calendarSystemPermissionGranted',
    'calendarSystemPermissionUndetermined',
    'calendarSystemPermissionDenied',
    'calendarSystemPermissionUnsupported',
    'calendarSystemRequestAccess',
    'calendarSystemDeniedHint',
    'calendarPushTitle',
    'calendarPushDesc',
    'calendarPushEnable',
    'calendarPushTarget',
    'calendarPushManagedTarget',
    'calendarPushRefresh',
    'calendarPushLoading',
    'calendarPushTargetHint',
    'syncFolderLocation',
    'savePath',
    'browse',
    'syncNow',
    'syncing',
    'syncQueued',
    'pathHint',
    'webdavUrl',
    'webdavUsername',
    'webdavPassword',
    'webdavSave',
    'testConnection',
    'webdavTestHint',
    'webdavTestAccessibility',
    'webdavHint',
    'allowInsecureHttp',
    'allowInsecureHttpHint',
    'cloudUrl',
    'cloudToken',
    'cloudRememberToken',
    'cloudRememberTokenHint',
    'cloudSave',
    'cloudHint',
    'cloudProvider',
    'cloudProviderSelfHosted',
    'cloudProviderDropbox',
    'cloudProviderCloudkit',
    'cloudkitDesc',
    'dropboxAppKey',
    'dropboxAppKeyHint',
    'dropboxRedirectUri',
    'dropboxStatus',
    'dropboxConnected',
    'dropboxNotConnected',
    'dropboxConnect',
    'dropboxDisconnect',
    'dropboxTest',
    'dropboxTestReachable',
    'dropboxTestFailed',
    'obsidianVault',
    'obsidianVaultDesc',
    'obsidianEnable',
    'obsidianVaultPath',
    'obsidianVaultPathHint',
    'obsidianDetectedVaults',
    'obsidianScanFolders',
    'obsidianScanFoldersHint',
    'obsidianInboxFile',
    'obsidianInboxFileHint',
    'obsidianDataview',
    'obsidianDataviewDesc',
    'obsidianDataviewMetadata',
    'obsidianDataviewMetadataHint',
    'obsidianTaskNotes',
    'obsidianTaskNotesDesc',
    'obsidianTaskNotesIncludeArchived',
    'obsidianTaskNotesIncludeArchivedHint',
    'obsidianNewTaskFormat',
    'obsidianNewTaskFormatHint',
    'obsidianNewTaskFormatAuto',
    'obsidianNewTaskFormatInline',
    'obsidianNewTaskFormatTaskNotes',
    'obsidianWatching',
    'obsidianWatcherUnavailable',
    'obsidianSave',
    'obsidianRemove',
    'obsidianRescan',
    'obsidianRescanning',
    'obsidianLastScanned',
    'obsidianNeverScanned',
    'obsidianMissingMarker',
    'obsidianChooseVaultFailed',
    'obsidianSaveFailed',
    'obsidianRemoveFailed',
    'obsidianScanFailed',
    'obsidianScanSuccess',
    'emailCapture',
    'emailCaptureDesc',
    'emailCaptureHost',
    'emailCapturePort',
    'emailCaptureUsername',
    'emailCapturePassword',
    'emailCapturePasswordHint',
    'emailCapturePasswordStored',
    'emailCaptureFolder',
    'emailCaptureFolderHint',
    'emailCaptureSave',
    'emailCaptureRemove',
    'emailCaptureCheckNow',
    'emailCaptureChecking',
    'emailCaptureLastChecked',
    'emailCaptureNeverChecked',
    'emailCaptureImportedCount',
    'emailCaptureSaveFailed',
    'lastSync',
    'lastSyncNever',
    'lastSyncSuccess',
    'lastSyncError',
    'lastSyncConflict',
    'lastSyncConflicts',
    'lastSyncSkew',
    'lastSyncAdjusted',
    'lastSyncConflictIds',
    'syncConflictKeptThisDevice',
    'syncConflictKeptOtherDevice',
    'syncConflictChanged',
    'syncConflictDeleteRestore',
    'syncConflictMore',
    'syncHistory',
    'recoverySnapshots',
    'recoverySnapshotsDesc',
    'recoverySnapshotsLoading',
    'recoverySnapshotsEmpty',
    'recoverySnapshotsRestore',
    'recoverySnapshotsConfirm',
    'recoverySnapshotsConfirmTitle',
    'recoverySnapshotsConfirmCancel',
    'about',
    'version',
    'installChannel',
    'developer',
    'website',
    'github',
    'documentation',
    'sponsorProject',
    'license',
    'feedback',
    'feedbackDesc',
    'feedbackCategory',
    'feedbackCategoryBug',
    'feedbackCategoryFeature',
    'feedbackCategoryOther',
    'feedbackMessage',
    'feedbackMessagePlaceholder',
    'feedbackMessagePlaceholderBug',
    'feedbackMessagePlaceholderFeature',
    'feedbackMessagePlaceholderOther',
    'feedbackWhere',
    'feedbackWherePlaceholder',
    'feedbackWhereMessagePrefix',
    'feedbackWhereInbox',
    'feedbackWhereFocus',
    'feedbackWhereProjects',
    'feedbackWhereReview',
    'feedbackWhereSettings',
    'feedbackWhereSync',
    'feedbackWhereImportExport',
    'feedbackWhereNotifications',
    'feedbackWhereOther',
    'feedbackEmail',
    'feedbackEmailPlaceholder',
    'feedbackIncludeDiagnostics',
    'feedbackIncludeDiagnosticsDesc',
    'feedbackPrivacy',
    'feedbackSubmit',
    'feedbackSending',
    'feedbackSent',
    'feedbackFailed',
    'feedbackUnavailable',
    'feedbackUnavailableDesc',
    'feedbackOpenGitHubIssue',
    'feedbackRequired',
    'feedbackInvalidEmail',
    'checkForUpdates',
    'checkStoreUpdates',
    'checking',
    'upToDate',
    'updateAvailable',
    'checkFailed',
    'storeUpdateHint',
    'download',
    'downloadStarting',
    'downloadStarted',
    'downloadFailed',
    'downloadChecksumMismatch',
    'downloadRecommended',
    'downloadAURHint',
    'changelog',
    'noChangelog',
    'later',
    'linuxUpdateHint',
    'saved',
    'selectSyncFolderTitle',
    'selectObsidianVaultTitle',
    'system',
    'light',
    'dark',
    'eink',
    'nord',
    'sepia',
    'close',
] as const;

export type SettingsLabels = Record<(typeof SETTINGS_LABEL_KEYS)[number], string>;

// Maps a settings label key to its i18n key when it isn't simply
// `settings.<key>` — either because the string is shared with another part
// of the app (e.g. `back` -> `common.back`) or core spells it differently.
export const labelKeyOverrides: Partial<Record<keyof SettingsLabels, string>> = {
    back: 'common.back',
    close: 'common.close',
    inboxModeGuided: 'process.modeGuided',
    inboxModeQuick: 'process.modeQuick',
    keybindings: 'keybindings.helpTitle',
    keybindingsDesc: 'settings.keybindingsDesc',
    keybindingStandard: 'keybindings.style.standard',
    keybindingVim: 'keybindings.style.vim',
    keybindingEmacs: 'keybindings.style.emacs',
    viewShortcuts: 'keybindings.openHelp',
    dateFormat: 'settings.dateFormat',
    dateFormatSystem: 'settings.dateFormatSystem',
    dateFormatDmy: 'settings.dateFormatDmy',
    dateFormatMdy: 'settings.dateFormatMdy',
    dateFormatYmd: 'settings.dateFormatYmd',
    calendarSystem: 'settings.calendarSystem',
    calendarSystemGregorian: 'settings.calendarSystemGregorian',
    calendarSystemJalali: 'settings.calendarSystemJalali',
    timeFormat: 'settings.timeFormat',
    timeFormatSystem: 'settings.timeFormatSystem',
    timeFormat12h: 'settings.timeFormat12h',
    timeFormat24h: 'settings.timeFormat24h',
    taskEditorLayoutReset: 'settings.resetToDefault',
    autoArchiveDayUnit: 'common.days',
    taskEditorFieldStatus: 'taskEdit.statusLabel',
    taskEditorFieldProject: 'taskEdit.projectLabel',
    taskEditorFieldSection: 'taskEdit.sectionLabel',
    taskEditorFieldArea: 'taskEdit.areaLabel',
    taskEditorFieldPriority: 'taskEdit.priorityLabel',
    taskEditorFieldEnergyLevel: 'taskEdit.energyLevel',
    taskEditorFieldAssignedTo: 'taskEdit.assignedTo',
    taskEditorFieldContexts: 'taskEdit.contextsLabel',
    taskEditorFieldDescription: 'taskEdit.descriptionLabel',
    taskEditorFieldLocation: 'taskEdit.locationLabel',
    taskEditorFieldTags: 'taskEdit.tagsLabel',
    taskEditorFieldTimeEstimate: 'taskEdit.timeEstimateLabel',
    taskEditorFieldRecurrence: 'taskEdit.recurrenceLabel',
    taskEditorFieldStartTime: 'taskEdit.startDateLabel',
    taskEditorFieldDueDate: 'taskEdit.dueDateLabel',
    taskEditorFieldReviewAt: 'taskEdit.reviewDateLabel',
    taskEditorFieldAttachments: 'attachments.title',
    taskEditorFieldChecklist: 'taskEdit.checklist',
    taskEditorFieldTextDirection: 'taskEdit.textDirectionLabel',
} as const;

// English settings labels, resolved from core's i18n locale, keyed the same
// way SettingsView builds its `t` prop. Used by settings page tests that need
// a real (not mocked) SettingsLabels object; components should get `t` from
// SettingsView instead.
export function getEnglishSettingsLabels(): SettingsLabels {
    const result = {} as SettingsLabels;
    SETTINGS_LABEL_KEYS.forEach((key) => {
        const i18nKey = labelKeyOverrides[key] ?? `settings.${key}`;
        result[key] = getEnglishI18nValue(i18nKey) ?? key;
    });
    return result;
}

// Search index source of truth: for each settings page, the label keys of the
// settings that page actually renders. The sidebar search derives its keywords
// from the *translated* values of these keys, so searchable terms stay
// localized and cannot drift when new settings are added to a page. This
// roster now lives in core (packages/core/src/settings-search-keys.ts) so
// mobile can derive its own row keywords from the same data instead of
// hand-listing a second copy — keep it in step with the pages under
// ./settings and the nav items in SettingsView.
export const SETTINGS_PAGE_LABEL_KEYS: Record<string, ReadonlyArray<keyof SettingsLabels>> =
    SETTINGS_SEARCH_PAGE_KEYS as Record<string, ReadonlyArray<keyof SettingsLabels>>;

// Combine the label-derived keywords for a page with a hand-curated synonym
// list. Synonyms supplement the localized labels (e.g. "dark mode", "autostart")
// but are never the primary index. Duplicates and empty values are dropped.
export function buildNavKeywords(
    t: SettingsLabels,
    labelKeys: ReadonlyArray<keyof SettingsLabels> = [],
    synonyms: ReadonlyArray<string> = [],
): string[] {
    const fromLabels = labelKeys
        .map((key) => t[key])
        .filter((value): value is string => Boolean(value && value.trim()));
    return Array.from(new Set([...fromLabels, ...synonyms]));
}
